/*
 * generated by Xtext 2.12.0
 */
package co.gov.dian.xtext.arquitecturadian.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import co.gov.dian.xtext.arquitecturadian.dsl.sql.Aplication

@RunWith(XtextRunner)
@InjectWith(SqlInjectorProvider)
class SqlParsingTest {
	@Inject
	ParseHelper<Aplication> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
