/*
 * generated by Xtext 2.12.0
 */
package co.gov.dian.xtext.arquitecturadian.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SqlRuntimeModule extends AbstractSqlRuntimeModule {
}
