/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 02-abr.-2019 4:34:38 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

Aplication Exportacion 

package "co.gov.dian.muisca.exportacion"

sufijoPkg "alianzapacifico"

database 

CREATE TABLE   PROCESO_DOCUMENTOS 
(
	 IDE_DOCUMENTO_PROCESADO  NUMBER(16) NOT NULL,	 
	 IDE_TIPO_PROCESO  NUMBER(8) NOT NULL,	
	 COD_ESTADO  CHAR(1) NOT NULL,	
	 VAL_LOG_ERROR  VARCHAR2(2000),	
	 FEC_PRIMERA_EJECUCION  TIMESTAMP,	
	 FEC_ULTIMA_EJECUCION  TIMESTAMP NOT NULL,	
	 NUM_INTENTOS  NUMBER(2) NOT NULL,	
	 CONSTRAINT  PRDO_PK 
	 PRIMARY KEY ( IDE_TIPO_PROCESO , IDE_DOCUMENTO_PROCESADO )
)
;