Aplication InformacionExtranjera 

package "co.gov.dian.muisca.informacionextranjera"

sufijoPkg "crs"

database 

CREATE TABLE  IEX_ARCHIVOS_REPORTE_CRS @TableDetail( nombreClase "ArchivoReporteCrs")
(
	IDE_PERSONA_RUT NUMBER(10) NOT NULL,
	IDE_ARCHIVO NUMBER(10) NOT NULL,
	NUM_ANIO NUMBER(4) NOT NULL,
	IDE_DOCUMENTO_REPORTE NUMBER(17) NOT NULL,
	NUM_REPETICION_DOC_REPORTE NUMBER(4) NOT NULL,
	FEC_FORMALIZACION NUMBER(8) ,
	COD_PAIS_RECEPTOR VARCHAR2(3) NOT NULL,	
	NUM_CUENTAS NUMBER(8) NOT NULL,	
	IND_ESTADO VARCHAR2(1) NOT NULL,
	IDE_USUARIO_CAMBIO NUMBER(10) NOT NULL,	
	FEC_CAMBIO TIMESTAMP NOT NULL,	
	NIV_ESCRITURA NUMBER(1) NOT NULL,
	NIV_LECTURA NUMBER(1) NOT NULL,	
	IDE_UUID VARCHAR2(32) NOT NULL,
	CONSTRAINT ARRE_PK
	PRIMARY KEY (IDE_PERSONA_RUT,IDE_ARCHIVO,NUM_ANIO,IDE_DOCUMENTO_REPORTE,NUM_REPETICION_DOC_REPORTE)
);
